=head1 NAME

CHANGES - List of revisions

=head1 Revision History

This document contains list of bug fixes and feature additions to SWISH-E.

=head2 Version 2.2

Release Date: ???????

Many large changes were made internally in the code, some for performance reasons, some for feature
changes and additions, and some to prepare for new features in later versions of SWISH-E.

=over 4

=item * Internal data stored as Properties

Pre 2.2 some internal data was stored in fixed locations within the index, namely the
file name, file size, and title.  2.2 introduced new internal data such as the last modified date, and
document summaries.
This data is considered I<meta data> since it is data about a document.
Instead of adding new data to the internal structure of the index file, it was decided to use the MetaNames
and PropertyNames feature of swish to store this meta information.
This allows for new meta data to be added at a later time (e.g. Content-type), and provides an easy and customizable
way to print results with the C<-p> switch and the new C<-x> switch.
In addition, this data can now be sorted by this internal data.

For example, to sort by the rank and title:

    swish-e -w foo -s swishrank desc swishtitle asc

=item * New "prog" document source indexing method

You can now use -S prog to use an external program to supply documents
to swish.  This program can be used to spider web servers, index databases,
or to convert any type of document into html, xml, or text, so it can be
indexed by swish.

=back

Changes to Configuration File Directives.  Please see L<SWISH-CONFIG|SWISH-CONFIG> for
more info.

=over 4

=item * New directives: IndexContents and DefaultContents

Previously, swish parsed all documents as HTML documents.  Now swish knows how to parse HTML, TXT, and XML
documents.  The IndexContents and DefaultContents tells swish how to index files by their extension.

=item * New directive: UndefinedMetaTags [error|ignore|index|auto]

This describes what to do when a meta tag is found in a document that is not listed in the MetaNames directive.

=item * New directive: IgnoreTags

Will ignore listed tags in XML files

=item * New directive: SwishProgParameters *list of words*

Passess words listed to the external swish-e program.

=item * New directive: ConvertHTMLEntities [yes|no]

Disables parsing and conversion of HTML entities.

=back

Changes to command line arguments.  See L<SWISH-RUN|SWISH-RUN> for documentation on these
switches.

=over 4

=item * New command line argument C<-x>

Provides additional header output and allows for a I<format string> to describe what data to print.

=item * New command line argument C<-k>

Prints words stored in the swish index.

=item * New command line argument C<-N>

Provides a way to do incremental indexing.  You pass C<-N> a path to a file
and only files newer than the last modified date of that file will be indexed.

=item * Enhanced command line argument C<-D>

When C<-D> is used with C<-v 4> additional debugging data is printed.

=item * Enhanced command line argument C<-d>

Now -d can accept some back-slashed characters to be used as output separators.

=item * Enhanced command line argument C<-P>

Now -P sets the phrase delimiter character in searches.


=back

