=head1 NAME

The SWISH-E README File

=head1 What is SWISH-E?

SWISH-E is B<S>imple B<W>eb B<I>ndexing B<S>ystem for B<H>umans - B<E>nhanced.
SWISH-E can quickly and easily index directories of files or remote web sites and search the generated
indexes.

SWISH was created by Kevin Hughes to fill the need of the growing number of Web administrators on the
Internet - many of the indexing systems were not well documented, were hard to use and install,
and were too complex for their own good. The system was widely used for several years,
long enough to collect some bug fixes and requests for enhancements.

In Fall 1996, The Library of UC Berkeley received permission from Kevin Hughes to implement bug fixes and
enhancements to the original binary. The result is SWISH-Enhanced or SWISH-E, brought to you by the
SWISH-E Development Team.

SWISH-E version 2 represents a major rewrite of the code and the addition of many new features.

=head2 Key features

=over 4

=item *

Quickly index a large number of documents in different formats
including text, HTML, and XML

=item *

Includes a web spider for indexing remote documents over HTTP

=item *

Use "filters" to index any type of file such as PDF, gzip, or Postscript

=item *

Use an external program to supply documents to swish, such as an advanced
spider for your web server, or a program to read and format records from a relational
database management system (RDBMS).

=item *

Document "properties" (some subset of the source document, usually
defined as a META or XML elements) may be stored in the index and
returned with search results

=item *

Document summaries can be returned with each search

=item *

Word stemming and soundex indexing

=item *

Phrase searching and wildcard searching

=item *

Results can be sorted by relevance or by any number of properties
in ascending or decending order

=item *

Limit searches to parts of documents such as certain HTML tags
(META, TITLE, comments, etc.) or to XML elements.

=item *

SWISH-E is fast.

=item *

It's open source and FREE!  You can customize SWISH-E and you
can contribute your fancy new features to the project.

=back


=head1 Where do I get SWISH-E?

The current version of SWISH-E can be found at:

http://sunsite.berkeley.edu/SWISH-E/

Please make sure you use a current version of swish-e.

Information about Windows binary distributions can also be
found at this site.

=head1 How Do I Install Swish?

Read the L<INSTALL|INSTALL> page.  Information on specific ports
(VMS and Win32) can be found in sub-directories of the C<src> directory.

The Windows binary can be found in the C<src/win32> directory.


=head1 The SWISH-E Documentation

Documetation is provided in the SWISH-E distribution package in two forms, POD (Plain Old Documentation),
and in html format.  The POD documentation is in the F<pod> directory, and the HTML documentation is in the
F<html> directory, of course.

The distribution make files can also generate the documentation in these formats:

    Postscript
    PDF (Adobe Acrobat)
    system man pages

You may also build a "split" version of the documentation where each topic heading is a separate
web page.  Building the split version also creates a SWISH-E index of the documentation that makes
the documentation searchable via the included Perl CGI program.

Buiding these other forms of documentation require aditional helper applications -- most modern Linux
distributions will include all that's needed.  At least mine does...  You shouldn't have a problem
if you have kept your perl and perl libraries up to date.

Online documentation can be found at the SWISH-E web site listed above.

See L<INSTALL|INSTALL> for information on creating the PDF and Postscript
versions of the documentation, and for information on installing the SWISH-* documentation as Unix man(1) pages.


=head2 How do I read the SWISH-E documentation?

The SWISH-E documentation is in POD format, and the documentation can be found in the F<pod>
directory.  POD documentation is displayed by
the "perldoc" command that is included with every Perl installation.
For example, to view the swish-e installation documentation page called "INSTALL", type

   perldoc pod/INSTALL

or to make life easier,

   cd pod
   perldoc INSTALL
   perldoc SWISH-RUN

Complain to your system administrator if the C<perldoc> command is not available on your machine.

=head2  Included Documentation

The following documentation is included in this SWISH-E distribution:

=over 4

=item *

L<README|README> --  this file

=item *

L<INSTALL|INSTALL>  -- Installation and basic usage instructions

=item *

L<SWISH-CONFIG|SWISH-CONFIG> -- Configuration File Directives

=item *

L<SWISH-RUN|SWISH-RUN> -- Running Swish and Command Line Switches

=item *

L<SWISH-SEARCH|SWISH-SEARCH> --All about Searching with SWISH-E

=item *

L<SWISH-FAQ|SWISH-FAQ> -- Common questions, and some answers

=item *

L<SWISH-LIBRARY|SWISH-LIBRARY> -- Interface to the SWISH-E C library

=item *

L<SWISH-PERL|SWISH-PERL> -- Instructions for using the Perl library

=item *

L<CHANGES|CHANGES> -- List of feature changes and bug fixes

=back

=head2 Document Generation

The SWISH-E documentation in HTML format was created with Pod::HtmlPsPdf, a package of Perl modules written
and/or modified by Stas Bekman to automate the conversion of documents in pod format (see perldoc perlpod)
to HTML, Postscript, and PDF.  A slightly modified version of this package is include with the SWISH-E distribution
and used for building the HTML.  As distributed, SWISH-E contains only the pod and HTML documentation.
See L<INSTALL|INSTALL> for instructions on creating man(1), Postscript, and PFD formats.

Thanks, Stas, for your help!

=head1 What's included in the SWISH-E distribution?

Here's an overview of the directories included in the swish-e distribution:

=over 3

=item conf/

Example swish-e configuration setups to help you get started.
In the C<stopwords> sub-directory are
a number of stopword files for different languages.

=item doc/

Contains files required for building the HTML, PDF, and Postscript documentation.

=item example/

This contains a sample CGI front-end for running swish-e.

=item filter-bin/

Sample programs to use with swish-e's "filters".  Examples include
PDF, MS Word, and binary strings filters.

=item html/

The documentation in HTML format.

=item perl/

The perl interface to the swish-e C library.

=item pod/

The documentation in perldoc (pod) format.

=item prog-bin/

Example programs and modules to use with the "prog" document source
access method.  Examples include a web spider, and a program to filter
pdf and MS word documents.

=item src/

This directory contains the source code for swish-e.  OS-specific directories are also
found here.

=item tests/

The documents used for running C<make test>.


=back


=head1 Where do I get help with SWISH-E?

If you need help with installing or using SWISH-E please subscribe to
the SWISH-E mailing list.  See visit the SWISH-E web site listed above
for information on subscribing to the SWISH-E list.

Before posting any questions please read
L<QUESTIONS AND TROUBLESHOOTING|INSTALL/"QUESTIONS AND TROUBLESHOOTING"> in the L<INSTALL|INSTALL>
documentation page.

=head1 Speling mistakes

Please contact the SWISH-E list with corrections to this documentation.  Any help
in cleaning up the docs will be appreciated!

=head1 SWISH-E Development

SWISH-E is currently being developed as an open source project on SourceForge
http://sourceforge.net.

See http://sourceforge.net/projects/swishe/ for more information.

=head1 Document Info

Each document in the SWISH-E distribution contains this section.  It refers only to the specific
page it's located in, and not to the SWISH-E program or the documentation as a whole.

$Id$

.


