#! /bin/sh

echo "$0 - for initialization of swish-e build environemnt"
echo "     not needed for user building"


#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --copy --include-deps

set -x

aclocal -I config \
 && libtoolize --force --copy \
 && autoheader \
 && automake --add-missing --copy --foreign \
 && autoconf \
 && rm -f config.cache
