/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypePrettyName  SWIG_Python_TypePrettyName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(const char *)     SWIG_TypePrettyName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *swig_type_list_handle;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *swig_type_list_handle;
  *swig_type_list_handle = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Return the pretty name associated with this type,
   that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME(const char *)
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/* 
   Compare two type names skipping the space characters, therefore
   "char*" == "char *" and "Class<int>" == "Class<int >", etc.

   Return 0 when the two name types are equivalent, as in
   strncmp, but skipping ' '.
*/
static int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
static int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}
  

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = *swig_type_list_handle;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = *swig_type_list_handle;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * pyrun.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)
 
/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

typedef double (*py_objasdbl_conv)(PyObject *obj);

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);


#else


/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,                                  /* Number of items in variable part (ob_size) */
  (char *)"swigvarlink",              /* Type name (tp_name) */
  sizeof(swig_varlinkobject),         /* Basic size (tp_basicsize) */
  0,                                  /* Itemsize (tp_itemsize) */
  0,                                  /* Deallocator (tp_dealloc) */ 
  (printfunc) swig_varlink_print,     /* Print (tp_print) */
  (getattrfunc) swig_varlink_getattr, /* get attr (tp_getattr) */
  (setattrfunc) swig_varlink_setattr, /* Set attr (tp_setattr) */
  0,                                  /* tp_compare */
  (reprfunc) swig_varlink_repr,       /* tp_repr */
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_sequence */
  0,                                  /* tp_as_mapping */
  0,                                  /* tp_hash */
  0,                                  /* tp_call */
  0,                                  /* tp_str */
  0,                                  /* tp_getattro */
  0,                                  /* tp_setattro */
  0,                                  /* tp_as_buffer */
  0,                                  /* tp_flags */
  0,                                  /* tp_doc */
  0,                                  /* tp_traverse */
  0,                                  /* tp_clear */
  0,                                  /* tp_richcompare */
  0,                                  /* tp_weaklistoffset */
#if PY_VERSION_HEX >= 0x02020000
  0,                                  /* tp_iter */
  0,                                  /* tp_iternext */
  0,                                  /* tp_methods */
  0,                                  /* tp_members */
  0,                                  /* tp_getset */
  0,                                  /* tp_base */
  0,                                  /* tp_dict */
  0,                                  /* tp_descr_get */
  0,                                  /* tp_descr_set */
  0,                                  /* tp_dictoffset */
  0,                                  /* tp_init */
  0,                                  /* tp_alloc */
  0,                                  /* tp_new */
  0,                                  /* tp_free */
  0,                                  /* tp_is_gc */
  0,                                  /* tp_bases */
  0,                                  /* tp_mro */
  0,                                  /* tp_cache */
  0,                                  /* tp_subclasses */
  0,                                  /* tp_weaklist */
#endif
#if PY_VERSION_HEX >= 0x02030200
  0,                                  /* tp_del */
#endif
#ifdef COUNT_ALLOCS
  /* these must be last */
  0,                                  /* tp_alloc */
  0,                                  /* tp_free */
  0,                                  /* tp_maxalloc */
  0,                                  /*  tp_next */
#endif
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AS_STRING(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject_SetAttrString(pyobj,(char*)"thisown",Py_False);
  }
  return 0;

type_error:
  PyErr_Clear();
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      PyErr_Format(PyExc_TypeError, 
		   "Type error. Got %s, expected %s",
		   c, ty->name);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AS_STRING(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      PyErr_Format(PyExc_TypeError, 
		   "Type error. Got %s, expected %s",
		   c, ty->name);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject_SetAttrString(inst,(char*)"thisown",Py_True);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      if (constants[i].pvalue) {
	obj = PyString_FromString((char *) constants[i].pvalue);
      } else {
	Py_INCREF(Py_None);
	obj = Py_None;
      }
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_SW_SEARCH swig_types[0] 
#define  SWIGTYPE_SW_HANDLE swig_types[1] 
#define  SWIGTYPE_p_time_t swig_types[2] 
#define  SWIGTYPE_p_SWISH_HEADER_TYPE swig_types[3] 
#define  SWIGTYPE_p_void swig_types[4] 
#define  SWIGTYPE_p_p_char swig_types[5] 
#define  SWIGTYPE_p_char swig_types[6] 
#define  SWIGTYPE_SW_RESULTS swig_types[7] 
#define  SWIGTYPE_p_u_PropValue1 swig_types[8] 
#define  SWIGTYPE_p_FILE swig_types[9] 
#define  SWIGTYPE_p_PropValue swig_types[10] 
#define  SWIGTYPE_SW_RESULT swig_types[11] 
#define  SWIGTYPE_SW_FUZZYWORD swig_types[12] 
#define  SWIGTYPE_p_SWISH_HEADER_VALUE swig_types[13] 
static swig_type_info *swig_types[15];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _swish.so
  ------------------------------------------------*/
#define SWIG_init    init_swish

#define SWIG_name    "_swish"

/* Auxiliar swig  macros that appear in the header */

#define SWIG_OLDOBJ  1
#define SWIG_NEWOBJ  SWIG_OLDOBJ + 1
#define SWIG_PYSTR   SWIG_NEWOBJ + 1

#ifdef __cplusplus
#define SWIGSTATICINLINE(a) static inline a
#define SWIGSTATIC(a) static a
#define swig_new_array(size,Type) (new Type[(size)])
#define swig_delete(cptr) delete cptr
#define swig_delete_array(cptr) delete[] cptr
#define swig_const_cast(a,Type) const_cast<Type >(a)
#define swig_static_cast(a,Type) static_cast<Type >(a)
#define swig_reinterpret_cast(a,Type) reinterpret_cast<Type >(a)
#define swig_new_copy(ptr,Type) (new Type(*ptr))
#define swig_numeric_cast(a,Type) static_cast<Type >(a)

#else /* C case */

#define SWIGSTATICINLINE(a) static a
#define SWIGSTATIC(a) static a
#define swig_new_array(size,Type) ((Type*) malloc((size)*sizeof(Type)))
#define swig_delete(cptr) free((char*)cptr)
#define swig_delete_array(cptr) free((char*)cptr)
#define swig_const_cast(a,Type) (Type)(a)
#define swig_static_cast(a,Type) (Type)(a)
#define swig_reinterpret_cast(a,Type) (Type)(a)
#define swig_numeric_cast(a,Type) (Type)(a)
#define swig_new_copy(ptr,Type)  ((Type*)memcpy(malloc(sizeof(Type)),ptr,sizeof(Type)))

#endif /* __cplusplus */


/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_signed_SS_char PyInt_FromLong
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_unsigned_SS_char PyInt_FromLong
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_short PyInt_FromLong
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_unsigned_SS_short PyInt_FromLong
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_int PyInt_FromLong
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_long PyInt_FromLong
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_float PyFloat_FromDouble
/*@@*/
/*@/usr/share/swig1.3/python/pymacros.swg,63,SWIG_define@*/
#define SWIG_From_double PyFloat_FromDouble
/*@@*/


    #include "/usr/include/swish-e.h"


/* returns SWIG_OLDOBJ if the input is a raw char*, SWIG_PYSTR if is a PyString */
SWIGSTATIC(int)
SWIG_AsCharPtrAndSize(PyObject *obj, char** cptr, size_t* psize)
{
  static swig_type_info* pchar_info = 0;
  char* vptr = 0;
  if (!pchar_info) pchar_info = SWIG_TypeQuery("char *");
  if (SWIG_ConvertPtr(obj, (void**)&vptr, pchar_info, 0) != -1) {
    if (cptr) *cptr = vptr;
    if (psize) *psize = vptr ? (strlen(vptr) + 1) : 0;
    return SWIG_OLDOBJ;
  } else {
    if (PyString_Check(obj)) {
      if (cptr) {
	*cptr = PyString_AS_STRING(obj);
	if (psize) {
	  *psize = PyString_GET_SIZE(obj) + 1;
	}
      }
      return SWIG_PYSTR;
    }
  }
  if (cptr) {
    PyErr_SetString(PyExc_TypeError, "a string is expected");
  }
  return 0;
}


SWIGSTATICINLINE(int)
SWIG_AsCharPtr(PyObject *obj, char **val)
{
  char* cptr = 0;
  if (SWIG_AsCharPtrAndSize(obj, &cptr, (size_t*)(0))) {
    if (val) *val = cptr;
    return 1;
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "a char* is expected");
  }
  return 0;
}


SWIGSTATICINLINE(PyObject *)
SWIG_FromCharPtr(const char* cptr)
{ 
  if (cptr) {
    size_t size = strlen(cptr);
    if (size > INT_MAX) {
      return SWIG_NewPointerObj(swig_const_cast(cptr,char*), 
				SWIG_TypeQuery("char *"), 0);
    } else {
      if (size != 0) {
	return PyString_FromStringAndSize(cptr, size);
      } else {
	return PyString_FromString(cptr);
      }
    }
  }
  Py_INCREF(Py_None);
  return Py_None;
}


SWIGSTATICINLINE(int)
  SWIG_AsVal_unsigned_SS_long(PyObject * obj, unsigned long *val) 
{
  if (PyInt_Check(obj)) {
    long v = PyInt_AS_LONG(obj);
    if (v >= 0) {
      if (val) *val = v;
      return 1;
    }   
  }
  if (PyLong_Check(obj)) {
    unsigned long v = PyLong_AsUnsignedLong(obj);
    if (!PyErr_Occurred()) {
      if (val) *val = v;
      return 1;
    } else {
      if (!val) PyErr_Clear();
      return 0;
    }
  } 
  if (val) {
    PyErr_SetString(PyExc_TypeError, "an unsigned long is expected");
  }
  return 0;
}


SWIGSTATICINLINE(unsigned long)
SWIG_As_unsigned_SS_long(PyObject* obj)
{
  unsigned long v;
  if (!SWIG_AsVal_unsigned_SS_long(obj, &v)) {
    /*
      this is needed to make valgrind/purify happier.  the other
      solution is throw an exception, but since this code should work
      with plain C ....
     */
    memset((void*)&v, 0, sizeof(unsigned long));
  }
  return v;
}

  
SWIGSTATICINLINE(int)
SWIG_Check_unsigned_SS_long(PyObject* obj)
{
  return SWIG_AsVal_unsigned_SS_long(obj, (unsigned long*)0);
}


SWIGSTATICINLINE(PyObject* )
  SWIG_From_unsigned_SS_long(unsigned long value)
{
  return (value > LONG_MAX) ?
    PyLong_FromUnsignedLong(value) 
    : PyInt_FromLong(swig_numeric_cast(value,long)); 
}


#include <limits.h>


SWIGSTATICINLINE(int)
  SWIG_CheckLongInRange(long value, long min_value, long max_value,
			const char *errmsg)
{
  if (value < min_value) {
    if (errmsg) {
      PyErr_Format(PyExc_OverflowError, 
		   "value %ld is less than '%s' minimum %ld", 
		   value, errmsg, min_value);
    }
    return 0;    
  } else if (value > max_value) {
    if (errmsg) {
      PyErr_Format(PyExc_OverflowError,
		   "value %ld is greater than '%s' maximum %ld", 
		   value, errmsg, max_value);
    }
    return 0;
  }
  return 1;
}


SWIGSTATICINLINE(int)
  SWIG_AsVal_long(PyObject * obj, long* val)
{
  if (PyInt_Check(obj)) {
    if (val) *val = PyInt_AS_LONG(obj);
    return 1;
  }
  if (PyLong_Check(obj)) {
    long v = PyLong_AsLong(obj);
    if (!PyErr_Occurred()) {
      if (val) *val = v;
      return 1;
    } else {
      if (!val) PyErr_Clear();
      return 0;
    }
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "a long is expected");
  }
  return 0;
 }


#if INT_MAX != LONG_MAX
SWIGSTATICINLINE(int)
  SWIG_AsVal_int(PyObject *obj, int *val)
{ 
  const char* errmsg = val ? "int" : 0;
  long v;
  if (SWIG_AsVal_long(obj, &v)) {
    if (SWIG_CheckLongInRange(v, INT_MIN,INT_MAX, errmsg)) {
      if (val) *val = swig_numeric_cast(v, int);
      return 1;
    } else {
      return 0;
    }
  } else {
    PyErr_Clear();
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "an int is expected");
  }
  return 0;    
}
#else
SWIGSTATICINLINE(int)
  SWIG_AsVal_int(PyObject *obj, int *val)
{
  return SWIG_AsVal_long(obj,(long*)val);
}
#endif


SWIGSTATICINLINE(int)
SWIG_As_int(PyObject* obj)
{
  int v;
  if (!SWIG_AsVal_int(obj, &v)) {
    /*
      this is needed to make valgrind/purify happier.  the other
      solution is throw an exception, but since this code should work
      with plain C ....
     */
    memset((void*)&v, 0, sizeof(int));
  }
  return v;
}

  
SWIGSTATICINLINE(int)
SWIG_Check_int(PyObject* obj)
{
  return SWIG_AsVal_int(obj, (int*)0);
}


SWIGSTATIC(int)
SWIG_AsCharArray(PyObject *obj, char *val, size_t size)
{ 
  char* cptr; size_t csize;  
  if (SWIG_AsCharPtrAndSize(obj, &cptr, &csize)) {
    /* in C you can do:        

         char x[5] = "hello"; 

        ie, assing the array using an extra '0' char.
    */
    if ((csize == size + 1) && !(cptr[csize-1])) --csize;
    if (csize <= size) {
      if (val) {
	if (csize) memcpy(val, cptr, csize);
	if (csize < size) memset(val + csize, 0, size - csize);
      }
      return 1;
    }
  }
  if (val) {
    PyErr_Format(PyExc_TypeError, 
		 "a char array of maximum size %ld is expected", 
		 size);
  }
  return 0;
}


SWIGSTATICINLINE(int)
  SWIG_AsVal_char(PyObject *obj, char *val)
{
  const char* errmsg = val ? "char" : 0;
  long v;
  if (SWIG_AsVal_long(obj, &v)) {
    if (SWIG_CheckLongInRange(v, CHAR_MIN,CHAR_MAX, errmsg)) {
      if (val) *val = v;
      return 1;
    } else {
      return 0;
    }    
  } else {
    PyErr_Clear();
    return SWIG_AsCharArray(obj, val, 1);
  }
 }


SWIGSTATICINLINE(char)
SWIG_As_char(PyObject* obj)
{
  char v;
  if (!SWIG_AsVal_char(obj, &v)) {
    /*
      this is needed to make valgrind/purify happier.  the other
      solution is throw an exception, but since this code should work
      with plain C ....
     */
    memset((void*)&v, 0, sizeof(char));
  }
  return v;
}

  
SWIGSTATICINLINE(int)
SWIG_Check_char(PyObject* obj)
{
  return SWIG_AsVal_char(obj, (char*)0);
}


SWIGSTATICINLINE(int)
  SWIG_AsVal_double(PyObject *obj, double *val)
{
  if (PyFloat_Check(obj)) {
    if (val) *val = PyFloat_AS_DOUBLE(obj);
    return 1;
  }  
  if (PyInt_Check(obj)) {
    if (val) *val = PyInt_AS_LONG(obj);
    return 1;
  }
  if (PyLong_Check(obj)) {
    double v = PyLong_AsDouble(obj);
    if (!PyErr_Occurred()) {
      if (val) *val = v;
      return 1;
    } else {
      if (!val) PyErr_Clear();
      return 0;
    }
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "a double is expected");
  }
  return 0;
}


SWIGSTATICINLINE(double)
SWIG_As_double(PyObject* obj)
{
  double v;
  if (!SWIG_AsVal_double(obj, &v)) {
    /*
      this is needed to make valgrind/purify happier.  the other
      solution is throw an exception, but since this code should work
      with plain C ....
     */
    memset((void*)&v, 0, sizeof(double));
  }
  return v;
}

  
SWIGSTATICINLINE(int)
SWIG_Check_double(PyObject* obj)
{
  return SWIG_AsVal_double(obj, (double*)0);
}

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_SWISH_HEADER_VALUE_string_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SWISH_HEADER_VALUE_string_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    {
        if (arg2) {
            arg1->string = (char const *) malloc(strlen(arg2)+1);
            strcpy((char*)arg1->string,arg2);
        } else {
            arg1->string = 0;
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_string_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SWISH_HEADER_VALUE_string_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *) ((arg1)->string);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_string_list_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    char **arg2 = (char **) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SWISH_HEADER_VALUE_string_list_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_p_char,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (arg1) (arg1)->string_list = (char const **)arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_string_list_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    char **result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SWISH_HEADER_VALUE_string_list_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char **) ((arg1)->string_list);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_p_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_number_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    unsigned long arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SWISH_HEADER_VALUE_number_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (unsigned long)SWIG_As_unsigned_SS_long(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->number = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_number_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    unsigned long result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SWISH_HEADER_VALUE_number_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned long) ((arg1)->number);
    
    resultobj = SWIG_From_unsigned_SS_long((unsigned long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_boolean_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SWISH_HEADER_VALUE_boolean_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->boolean = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SWISH_HEADER_VALUE_boolean_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SWISH_HEADER_VALUE_boolean_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int) ((arg1)->boolean);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_SWISH_HEADER_VALUE(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_SWISH_HEADER_VALUE")) goto fail;
    result = (SWISH_HEADER_VALUE *)(SWISH_HEADER_VALUE *) calloc(1, sizeof(SWISH_HEADER_VALUE));
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_SWISH_HEADER_VALUE, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_SWISH_HEADER_VALUE(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SWISH_HEADER_VALUE *arg1 = (SWISH_HEADER_VALUE *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_SWISH_HEADER_VALUE",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_SWISH_HEADER_VALUE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * SWISH_HEADER_VALUE_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_SWISH_HEADER_VALUE, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_SwishHeaderNames(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char **result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishHeaderNames",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char **)SwishHeaderNames(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_p_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishIndexNames(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char **result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishIndexNames",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char **)SwishIndexNames(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_p_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishHeaderValue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *arg2 ;
    char *arg3 ;
    SWISH_HEADER_TYPE *arg4 = (SWISH_HEADER_TYPE *) 0 ;
    SWISH_HEADER_VALUE result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOO:SwishHeaderValue",&obj0,&obj1,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    if (!SWIG_AsCharPtr(obj2, (char**)&arg3)) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **)(&arg4),SWIGTYPE_p_SWISH_HEADER_TYPE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = SwishHeaderValue(arg1,(char const *)arg2,(char const *)arg3,arg4);
    
    {
        SWISH_HEADER_VALUE * resultptr;
        resultptr = (SWISH_HEADER_VALUE *) malloc(sizeof(SWISH_HEADER_VALUE));
        memmove(resultptr, &result, sizeof(SWISH_HEADER_VALUE));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_SWISH_HEADER_VALUE, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishResultIndexValue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    char *arg2 ;
    SWISH_HEADER_TYPE *arg3 = (SWISH_HEADER_TYPE *) 0 ;
    SWISH_HEADER_VALUE result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:SwishResultIndexValue",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **)(&arg3),SWIGTYPE_p_SWISH_HEADER_TYPE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = SwishResultIndexValue(arg1,(char const *)arg2,arg3);
    
    {
        SWISH_HEADER_VALUE * resultptr;
        resultptr = (SWISH_HEADER_VALUE *) malloc(sizeof(SWISH_HEADER_VALUE));
        memmove(resultptr, &result, sizeof(SWISH_HEADER_VALUE));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_SWISH_HEADER_VALUE, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishInit(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    SW_HANDLE result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishInit",&obj0)) goto fail;
    if (!SWIG_AsCharPtr(obj0, (char**)&arg1)) SWIG_fail;
    result = (SW_HANDLE)SwishInit(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_HANDLE, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishQuery(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *arg2 ;
    SW_RESULTS result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishQuery",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (SW_RESULTS)SwishQuery(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_RESULTS, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_New_Search_Object(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *arg2 ;
    SW_SEARCH result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:New_Search_Object",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (SW_SEARCH)New_Search_Object(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_SEARCH, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSetRefPtr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishSetRefPtr",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    SwishSetRefPtr(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSearch_parent(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishSearch_parent",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *)SwishSearch_parent(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishResults_parent(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishResults_parent",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *)SwishResults_parent(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishResult_parent(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishResult_parent",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *)SwishResult_parent(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_ResultsSetRefPtr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:ResultsSetRefPtr",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    ResultsSetRefPtr(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSetStructure(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishSetStructure",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    SwishSetStructure(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishPhraseDelimiter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    char arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishPhraseDelimiter",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (char)SWIG_As_char(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    SwishPhraseDelimiter(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSetSort(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishSetSort",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    SwishSetSort(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSetQuery(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishSetQuery",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    SwishSetQuery(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSetSearchLimit(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOO:SwishSetSearchLimit",&obj0,&obj1,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    if (!SWIG_AsCharPtr(obj2, (char**)&arg3)) SWIG_fail;
    if (!SWIG_AsCharPtr(obj3, (char**)&arg4)) SWIG_fail;
    result = (int)SwishSetSearchLimit(arg1,arg2,arg3,arg4);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishResetSearchLimit(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishResetSearchLimit",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    SwishResetSearchLimit(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishExecute(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    char *arg2 ;
    SW_RESULTS result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishExecute",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (SW_RESULTS)SwishExecute(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_RESULTS, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishHits(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishHits",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)SwishHits(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishParsedWords(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    char *arg2 ;
    SWISH_HEADER_VALUE result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishParsedWords",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = SwishParsedWords(arg1,(char const *)arg2);
    
    {
        SWISH_HEADER_VALUE * resultptr;
        resultptr = (SWISH_HEADER_VALUE *) malloc(sizeof(SWISH_HEADER_VALUE));
        memmove(resultptr, &result, sizeof(SWISH_HEADER_VALUE));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_SWISH_HEADER_VALUE, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishRemovedStopwords(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    char *arg2 ;
    SWISH_HEADER_VALUE result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishRemovedStopwords",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = SwishRemovedStopwords(arg1,(char const *)arg2);
    
    {
        SWISH_HEADER_VALUE * resultptr;
        resultptr = (SWISH_HEADER_VALUE *) malloc(sizeof(SWISH_HEADER_VALUE));
        memmove(resultptr, &result, sizeof(SWISH_HEADER_VALUE));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_SWISH_HEADER_VALUE, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishSeekResult(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    int arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishSeekResult",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    result = (int)SwishSeekResult(arg1,arg2);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishNextResult(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    SW_RESULT result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishNextResult",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (SW_RESULT)SwishNextResult(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_RESULT, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishResultPropertyStr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    char *arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishResultPropertyStr",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (char *)SwishResultPropertyStr(arg1,arg2);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishResultPropertyULong(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    char *arg2 ;
    unsigned long result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishResultPropertyULong",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (unsigned long)SwishResultPropertyULong(arg1,arg2);
    
    resultobj = SWIG_From_unsigned_SS_long((unsigned long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SW_ResultToSW_HANDLE(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    SW_HANDLE result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SW_ResultToSW_HANDLE",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (SW_HANDLE)SW_ResultToSW_HANDLE(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_HANDLE, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SW_ResultsToSW_HANDLE(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    SW_HANDLE result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SW_ResultsToSW_HANDLE",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (SW_HANDLE)SW_ResultsToSW_HANDLE(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_HANDLE, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Free_Search_Object(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_SEARCH arg1 = (SW_SEARCH) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Free_Search_Object",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    Free_Search_Object(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Free_Results_Object(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULTS arg1 = (SW_RESULTS) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Free_Results_Object",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    Free_Results_Object(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishClose(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishClose",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    SwishClose(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishError(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishError",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)SwishError(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishCriticalError(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishCriticalError",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)SwishCriticalError(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishAbortLastError(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishAbortLastError",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    SwishAbortLastError(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishErrorString(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishErrorString",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *)SwishErrorString(arg1);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishLastErrorMsg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishLastErrorMsg",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *)SwishLastErrorMsg(arg1);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_set_error_handle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    FILE *arg1 = (FILE *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:set_error_handle",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_FILE,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    set_error_handle(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishErrorsToStderr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":SwishErrorsToStderr")) goto fail;
    SwishErrorsToStderr();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishWordsByLetter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *arg2 ;
    char arg3 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:SwishWordsByLetter",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    arg3 = (char)SWIG_As_char(obj2); 
    if (PyErr_Occurred()) SWIG_fail;
    result = (char *)SwishWordsByLetter(arg1,arg2,arg3);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishStemWord(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_HANDLE arg1 = (SW_HANDLE) 0 ;
    char *arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishStemWord",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (char *)SwishStemWord(arg1,arg2);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishFuzzyWord(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    char *arg2 ;
    SW_FUZZYWORD result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SwishFuzzyWord",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    result = (SW_FUZZYWORD)SwishFuzzyWord(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_SW_FUZZYWORD, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishFuzzyWordList(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_FUZZYWORD arg1 = (SW_FUZZYWORD) 0 ;
    char **result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishFuzzyWordList",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char **)SwishFuzzyWordList(arg1);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_p_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishFuzzyWordCount(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_FUZZYWORD arg1 = (SW_FUZZYWORD) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishFuzzyWordCount",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)SwishFuzzyWordCount(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishFuzzyWordError(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_FUZZYWORD arg1 = (SW_FUZZYWORD) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishFuzzyWordError",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)SwishFuzzyWordError(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishFuzzyWordFree(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_FUZZYWORD arg1 = (SW_FUZZYWORD) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishFuzzyWordFree",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    SwishFuzzyWordFree(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_SwishFuzzyMode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SwishFuzzyMode",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *)SwishFuzzyMode(arg1);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_str_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:u_PropValue1_v_str_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    {
        if (arg1->v_str) free((char*)arg1->v_str);
        if (arg2) {
            arg1->v_str = (char *) malloc(strlen(arg2)+1);
            strcpy((char*)arg1->v_str,arg2);
        } else {
            arg1->v_str = 0;
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_str_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:u_PropValue1_v_str_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *) ((arg1)->v_str);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_int_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:u_PropValue1_v_int_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->v_int = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_int_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:u_PropValue1_v_int_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int) ((arg1)->v_int);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_date_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    time_t arg2 ;
    time_t *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:u_PropValue1_v_date_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&argp2),SWIGTYPE_p_time_t,
    SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2;
    if (arg1) (arg1)->v_date = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_date_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    time_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:u_PropValue1_v_date_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result =  ((arg1)->v_date);
    
    {
        time_t * resultptr;
        resultptr = (time_t *) malloc(sizeof(time_t));
        memmove(resultptr, &result, sizeof(time_t));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_time_t, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_float_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:u_PropValue1_v_float_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (double)SWIG_As_double(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->v_float = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_float_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:u_PropValue1_v_float_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (double) ((arg1)->v_float);
    
    resultobj = SWIG_From_double((double)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_ulong_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    unsigned long arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:u_PropValue1_v_ulong_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (unsigned long)SWIG_As_unsigned_SS_long(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->v_ulong = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_u_PropValue1_v_ulong_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    unsigned long result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:u_PropValue1_v_ulong_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned long) ((arg1)->v_ulong);
    
    resultobj = SWIG_From_unsigned_SS_long((unsigned long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_u_PropValue1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_u_PropValue1")) goto fail;
    result = (u_PropValue1 *)(u_PropValue1 *) calloc(1, sizeof(u_PropValue1));
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_u_PropValue1, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_u_PropValue1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    u_PropValue1 *arg1 = (u_PropValue1 *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_u_PropValue1",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * u_PropValue1_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_u_PropValue1, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_PropValue_datatype_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:PropValue_datatype_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->datatype = (PropType )arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_PropValue_datatype_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:PropValue_datatype_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int) ((arg1)->datatype);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_PropValue_value_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    u_PropValue1 *arg2 = (u_PropValue1 *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:PropValue_value_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_u_PropValue1,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (arg1) (arg1)->value = *arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_PropValue_value_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    u_PropValue1 *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:PropValue_value_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (u_PropValue1 *)& ((arg1)->value);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_u_PropValue1, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_PropValue_destroy_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:PropValue_destroy_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->destroy = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_PropValue_destroy_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:PropValue_destroy_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int) ((arg1)->destroy);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_PropValue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_PropValue")) goto fail;
    result = (PropValue *)(PropValue *) calloc(1, sizeof(PropValue));
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_PropValue, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_PropValue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_PropValue",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * PropValue_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_PropValue, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_getResultPropValue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    SW_RESULT arg1 = (SW_RESULT) 0 ;
    char *arg2 ;
    int arg3 ;
    PropValue *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:getResultPropValue",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    arg3 = (int)SWIG_As_int(obj2); 
    if (PyErr_Occurred()) SWIG_fail;
    result = (PropValue *)getResultPropValue(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_PropValue, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_freeResultPropValue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PropValue *arg1 = (PropValue *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:freeResultPropValue",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_PropValue,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    freeResultPropValue(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"SWISH_HEADER_VALUE_string_set", _wrap_SWISH_HEADER_VALUE_string_set, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_string_get", _wrap_SWISH_HEADER_VALUE_string_get, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_string_list_set", _wrap_SWISH_HEADER_VALUE_string_list_set, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_string_list_get", _wrap_SWISH_HEADER_VALUE_string_list_get, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_number_set", _wrap_SWISH_HEADER_VALUE_number_set, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_number_get", _wrap_SWISH_HEADER_VALUE_number_get, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_boolean_set", _wrap_SWISH_HEADER_VALUE_boolean_set, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_boolean_get", _wrap_SWISH_HEADER_VALUE_boolean_get, METH_VARARGS, NULL },
	 { (char *)"new_SWISH_HEADER_VALUE", _wrap_new_SWISH_HEADER_VALUE, METH_VARARGS, NULL },
	 { (char *)"delete_SWISH_HEADER_VALUE", _wrap_delete_SWISH_HEADER_VALUE, METH_VARARGS, NULL },
	 { (char *)"SWISH_HEADER_VALUE_swigregister", SWISH_HEADER_VALUE_swigregister, METH_VARARGS, NULL },
	 { (char *)"SwishHeaderNames", _wrap_SwishHeaderNames, METH_VARARGS, NULL },
	 { (char *)"SwishIndexNames", _wrap_SwishIndexNames, METH_VARARGS, NULL },
	 { (char *)"SwishHeaderValue", _wrap_SwishHeaderValue, METH_VARARGS, NULL },
	 { (char *)"SwishResultIndexValue", _wrap_SwishResultIndexValue, METH_VARARGS, NULL },
	 { (char *)"SwishInit", _wrap_SwishInit, METH_VARARGS, NULL },
	 { (char *)"SwishQuery", _wrap_SwishQuery, METH_VARARGS, NULL },
	 { (char *)"New_Search_Object", _wrap_New_Search_Object, METH_VARARGS, NULL },
	 { (char *)"SwishSetRefPtr", _wrap_SwishSetRefPtr, METH_VARARGS, NULL },
	 { (char *)"SwishSearch_parent", _wrap_SwishSearch_parent, METH_VARARGS, NULL },
	 { (char *)"SwishResults_parent", _wrap_SwishResults_parent, METH_VARARGS, NULL },
	 { (char *)"SwishResult_parent", _wrap_SwishResult_parent, METH_VARARGS, NULL },
	 { (char *)"ResultsSetRefPtr", _wrap_ResultsSetRefPtr, METH_VARARGS, NULL },
	 { (char *)"SwishSetStructure", _wrap_SwishSetStructure, METH_VARARGS, NULL },
	 { (char *)"SwishPhraseDelimiter", _wrap_SwishPhraseDelimiter, METH_VARARGS, NULL },
	 { (char *)"SwishSetSort", _wrap_SwishSetSort, METH_VARARGS, NULL },
	 { (char *)"SwishSetQuery", _wrap_SwishSetQuery, METH_VARARGS, NULL },
	 { (char *)"SwishSetSearchLimit", _wrap_SwishSetSearchLimit, METH_VARARGS, NULL },
	 { (char *)"SwishResetSearchLimit", _wrap_SwishResetSearchLimit, METH_VARARGS, NULL },
	 { (char *)"SwishExecute", _wrap_SwishExecute, METH_VARARGS, NULL },
	 { (char *)"SwishHits", _wrap_SwishHits, METH_VARARGS, NULL },
	 { (char *)"SwishParsedWords", _wrap_SwishParsedWords, METH_VARARGS, NULL },
	 { (char *)"SwishRemovedStopwords", _wrap_SwishRemovedStopwords, METH_VARARGS, NULL },
	 { (char *)"SwishSeekResult", _wrap_SwishSeekResult, METH_VARARGS, NULL },
	 { (char *)"SwishNextResult", _wrap_SwishNextResult, METH_VARARGS, NULL },
	 { (char *)"SwishResultPropertyStr", _wrap_SwishResultPropertyStr, METH_VARARGS, NULL },
	 { (char *)"SwishResultPropertyULong", _wrap_SwishResultPropertyULong, METH_VARARGS, NULL },
	 { (char *)"SW_ResultToSW_HANDLE", _wrap_SW_ResultToSW_HANDLE, METH_VARARGS, NULL },
	 { (char *)"SW_ResultsToSW_HANDLE", _wrap_SW_ResultsToSW_HANDLE, METH_VARARGS, NULL },
	 { (char *)"Free_Search_Object", _wrap_Free_Search_Object, METH_VARARGS, NULL },
	 { (char *)"Free_Results_Object", _wrap_Free_Results_Object, METH_VARARGS, NULL },
	 { (char *)"SwishClose", _wrap_SwishClose, METH_VARARGS, NULL },
	 { (char *)"SwishError", _wrap_SwishError, METH_VARARGS, NULL },
	 { (char *)"SwishCriticalError", _wrap_SwishCriticalError, METH_VARARGS, NULL },
	 { (char *)"SwishAbortLastError", _wrap_SwishAbortLastError, METH_VARARGS, NULL },
	 { (char *)"SwishErrorString", _wrap_SwishErrorString, METH_VARARGS, NULL },
	 { (char *)"SwishLastErrorMsg", _wrap_SwishLastErrorMsg, METH_VARARGS, NULL },
	 { (char *)"set_error_handle", _wrap_set_error_handle, METH_VARARGS, NULL },
	 { (char *)"SwishErrorsToStderr", _wrap_SwishErrorsToStderr, METH_VARARGS, NULL },
	 { (char *)"SwishWordsByLetter", _wrap_SwishWordsByLetter, METH_VARARGS, NULL },
	 { (char *)"SwishStemWord", _wrap_SwishStemWord, METH_VARARGS, NULL },
	 { (char *)"SwishFuzzyWord", _wrap_SwishFuzzyWord, METH_VARARGS, NULL },
	 { (char *)"SwishFuzzyWordList", _wrap_SwishFuzzyWordList, METH_VARARGS, NULL },
	 { (char *)"SwishFuzzyWordCount", _wrap_SwishFuzzyWordCount, METH_VARARGS, NULL },
	 { (char *)"SwishFuzzyWordError", _wrap_SwishFuzzyWordError, METH_VARARGS, NULL },
	 { (char *)"SwishFuzzyWordFree", _wrap_SwishFuzzyWordFree, METH_VARARGS, NULL },
	 { (char *)"SwishFuzzyMode", _wrap_SwishFuzzyMode, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_str_set", _wrap_u_PropValue1_v_str_set, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_str_get", _wrap_u_PropValue1_v_str_get, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_int_set", _wrap_u_PropValue1_v_int_set, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_int_get", _wrap_u_PropValue1_v_int_get, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_date_set", _wrap_u_PropValue1_v_date_set, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_date_get", _wrap_u_PropValue1_v_date_get, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_float_set", _wrap_u_PropValue1_v_float_set, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_float_get", _wrap_u_PropValue1_v_float_get, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_ulong_set", _wrap_u_PropValue1_v_ulong_set, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_v_ulong_get", _wrap_u_PropValue1_v_ulong_get, METH_VARARGS, NULL },
	 { (char *)"new_u_PropValue1", _wrap_new_u_PropValue1, METH_VARARGS, NULL },
	 { (char *)"delete_u_PropValue1", _wrap_delete_u_PropValue1, METH_VARARGS, NULL },
	 { (char *)"u_PropValue1_swigregister", u_PropValue1_swigregister, METH_VARARGS, NULL },
	 { (char *)"PropValue_datatype_set", _wrap_PropValue_datatype_set, METH_VARARGS, NULL },
	 { (char *)"PropValue_datatype_get", _wrap_PropValue_datatype_get, METH_VARARGS, NULL },
	 { (char *)"PropValue_value_set", _wrap_PropValue_value_set, METH_VARARGS, NULL },
	 { (char *)"PropValue_value_get", _wrap_PropValue_value_get, METH_VARARGS, NULL },
	 { (char *)"PropValue_destroy_set", _wrap_PropValue_destroy_set, METH_VARARGS, NULL },
	 { (char *)"PropValue_destroy_get", _wrap_PropValue_destroy_get, METH_VARARGS, NULL },
	 { (char *)"new_PropValue", _wrap_new_PropValue, METH_VARARGS, NULL },
	 { (char *)"delete_PropValue", _wrap_delete_PropValue, METH_VARARGS, NULL },
	 { (char *)"PropValue_swigregister", PropValue_swigregister, METH_VARARGS, NULL },
	 { (char *)"getResultPropValue", _wrap_getResultPropValue, METH_VARARGS, NULL },
	 { (char *)"freeResultPropValue", _wrap_freeResultPropValue, METH_VARARGS, NULL },
	 { NULL, NULL, 0, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__SW_SEARCH[] = {{"_SW_SEARCH", 0, "void *|SW_SEARCH", 0, 0, 0, 0},{"_SW_SEARCH", 0, 0, 0, 0, 0, 0},{"_SW_RESULT", 0, 0, 0, 0, 0, 0},{"_SW_HANDLE", 0, 0, 0, 0, 0, 0},{"_SW_RESULTS", 0, 0, 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{"_SW_FUZZYWORD", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__SW_HANDLE[] = {{"_SW_HANDLE", 0, "void *|SW_HANDLE", 0, 0, 0, 0},{"_SW_SEARCH", 0, 0, 0, 0, 0, 0},{"_SW_RESULT", 0, 0, 0, 0, 0, 0},{"_SW_HANDLE", 0, 0, 0, 0, 0, 0},{"_SW_RESULTS", 0, 0, 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{"_SW_FUZZYWORD", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_time_t[] = {{"_p_time_t", 0, "time_t *", 0, 0, 0, 0},{"_p_time_t", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_SWISH_HEADER_TYPE[] = {{"_p_SWISH_HEADER_TYPE", 0, "enum SWISH_HEADER_TYPE *|SWISH_HEADER_TYPE *", 0, 0, 0, 0},{"_p_SWISH_HEADER_TYPE", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_void[] = {{"_p_void", 0, "void *", 0, 0, 0, 0},{"_SW_SEARCH", 0, 0, 0, 0, 0, 0},{"_SW_RESULT", 0, 0, 0, 0, 0, 0},{"_SW_HANDLE", 0, 0, 0, 0, 0, 0},{"_SW_RESULTS", 0, 0, 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{"_SW_FUZZYWORD", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_p_char[] = {{"_p_p_char", 0, "char **", 0, 0, 0, 0},{"_p_p_char", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_char[] = {{"_p_char", 0, "char *", 0, 0, 0, 0},{"_p_char", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__SW_RESULTS[] = {{"_SW_RESULTS", 0, "void *|SW_RESULTS", 0, 0, 0, 0},{"_SW_SEARCH", 0, 0, 0, 0, 0, 0},{"_SW_RESULT", 0, 0, 0, 0, 0, 0},{"_SW_HANDLE", 0, 0, 0, 0, 0, 0},{"_SW_RESULTS", 0, 0, 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{"_SW_FUZZYWORD", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_u_PropValue1[] = {{"_p_u_PropValue1", 0, "u_PropValue1 *", 0, 0, 0, 0},{"_p_u_PropValue1", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_FILE[] = {{"_p_FILE", 0, "FILE *", 0, 0, 0, 0},{"_p_FILE", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_PropValue[] = {{"_p_PropValue", 0, "PropValue *", 0, 0, 0, 0},{"_p_PropValue", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__SW_RESULT[] = {{"_SW_RESULT", 0, "void *|SW_RESULT", 0, 0, 0, 0},{"_SW_RESULT", 0, 0, 0, 0, 0, 0},{"_SW_SEARCH", 0, 0, 0, 0, 0, 0},{"_SW_HANDLE", 0, 0, 0, 0, 0, 0},{"_SW_RESULTS", 0, 0, 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{"_SW_FUZZYWORD", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__SW_FUZZYWORD[] = {{"_SW_FUZZYWORD", 0, "void *|SW_FUZZYWORD", 0, 0, 0, 0},{"_SW_SEARCH", 0, 0, 0, 0, 0, 0},{"_SW_RESULT", 0, 0, 0, 0, 0, 0},{"_SW_HANDLE", 0, 0, 0, 0, 0, 0},{"_SW_RESULTS", 0, 0, 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{"_SW_FUZZYWORD", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_SWISH_HEADER_VALUE[] = {{"_p_SWISH_HEADER_VALUE", 0, "SWISH_HEADER_VALUE *", 0, 0, 0, 0},{"_p_SWISH_HEADER_VALUE", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__SW_SEARCH, 
_swigt__SW_HANDLE, 
_swigt__p_time_t, 
_swigt__p_SWISH_HEADER_TYPE, 
_swigt__p_void, 
_swigt__p_p_char, 
_swigt__p_char, 
_swigt__SW_RESULTS, 
_swigt__p_u_PropValue1, 
_swigt__p_FILE, 
_swigt__p_PropValue, 
_swigt__SW_RESULT, 
_swigt__SW_FUZZYWORD, 
_swigt__p_SWISH_HEADER_VALUE, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0, 0, 0, 0.0, 0, 0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
    PyDict_SetItemString(d,"SEARCHSWISH_H", SWIG_From_int((int)1));
    PyDict_SetItemString(d,"SWISH_NUMBER", SWIG_From_int((int)SWISH_NUMBER));
    PyDict_SetItemString(d,"SWISH_STRING", SWIG_From_int((int)SWISH_STRING));
    PyDict_SetItemString(d,"SWISH_LIST", SWIG_From_int((int)SWISH_LIST));
    PyDict_SetItemString(d,"SWISH_BOOL", SWIG_From_int((int)SWISH_BOOL));
    PyDict_SetItemString(d,"SWISH_WORD_HASH", SWIG_From_int((int)SWISH_WORD_HASH));
    PyDict_SetItemString(d,"SWISH_OTHER_DATA", SWIG_From_int((int)SWISH_OTHER_DATA));
    PyDict_SetItemString(d,"SWISH_HEADER_ERROR", SWIG_From_int((int)SWISH_HEADER_ERROR));
    PyDict_SetItemString(d,"IN_FILE_BIT", SWIG_From_int((int)0));
    PyDict_SetItemString(d,"IN_TITLE_BIT", SWIG_From_int((int)1));
    PyDict_SetItemString(d,"IN_HEAD_BIT", SWIG_From_int((int)2));
    PyDict_SetItemString(d,"IN_BODY_BIT", SWIG_From_int((int)3));
    PyDict_SetItemString(d,"IN_COMMENTS_BIT", SWIG_From_int((int)4));
    PyDict_SetItemString(d,"IN_HEADER_BIT", SWIG_From_int((int)5));
    PyDict_SetItemString(d,"IN_EMPHASIZED_BIT", SWIG_From_int((int)6));
    PyDict_SetItemString(d,"IN_META_BIT", SWIG_From_int((int)7));
    PyDict_SetItemString(d,"IN_FILE", SWIG_From_int((int)(1<<0)));
    PyDict_SetItemString(d,"IN_TITLE", SWIG_From_int((int)(1<<1)));
    PyDict_SetItemString(d,"IN_HEAD", SWIG_From_int((int)(1<<2)));
    PyDict_SetItemString(d,"IN_BODY", SWIG_From_int((int)(1<<3)));
    PyDict_SetItemString(d,"IN_COMMENTS", SWIG_From_int((int)(1<<4)));
    PyDict_SetItemString(d,"IN_HEADER", SWIG_From_int((int)(1<<5)));
    PyDict_SetItemString(d,"IN_EMPHASIZED", SWIG_From_int((int)(1<<6)));
    PyDict_SetItemString(d,"IN_META", SWIG_From_int((int)(1<<7)));
    PyDict_SetItemString(d,"IN_ALL", SWIG_From_int((int)((1<<0)|(1<<1)|(1<<2)|(1<<3)|(1<<4)|(1<<5)|(1<<6)|(1<<7))));
    PyDict_SetItemString(d,"PROP_UNDEFINED", SWIG_From_int((int)PROP_UNDEFINED));
    PyDict_SetItemString(d,"PROP_UNKNOWN", SWIG_From_int((int)PROP_UNKNOWN));
    PyDict_SetItemString(d,"PROP_STRING", SWIG_From_int((int)PROP_STRING));
    PyDict_SetItemString(d,"PROP_INTEGER", SWIG_From_int((int)PROP_INTEGER));
    PyDict_SetItemString(d,"PROP_FLOAT", SWIG_From_int((int)PROP_FLOAT));
    PyDict_SetItemString(d,"PROP_DATE", SWIG_From_int((int)PROP_DATE));
    PyDict_SetItemString(d,"PROP_ULONG", SWIG_From_int((int)PROP_ULONG));
}

